"""empty message

Revision ID: 31503ae9935a
Revises: 
Create Date: 2024-01-28 08:40:02.427450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31503ae9935a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_request')
    # ### end Alembic commands ###
