"""empty message

Revision ID: dc44a0bdc052
Revises: 31503ae9935a
Create Date: 2024-01-28 09:17:40.352350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc44a0bdc052'
down_revision = '31503ae9935a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('_username_country_city_uc', ['username', 'country_code', 'city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_request', schema=None) as batch_op:
        batch_op.drop_constraint('_username_country_city_uc', type_='unique')

    # ### end Alembic commands ###
